version: '3'

services:
  base: &base
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        EXECJS_RUNTIME: 'Node'
        NODE_ENV: 'production'
        RAILS_ENV: 'production'
        RAILS_SERVE_STATIC_FILES: 'true'
    tty: true
    stdin_open: true
    image: chatwoot:production
    env_file: .env

  rails:
    <<: *base
    image: chatwoot-rails:production
    depends_on:
      - sidekiq
    ports:
      - 3000:3000
    env_file: .env
    environment:
      - EXECJS_RUNTIME=Node
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
    entrypoint: docker/entrypoints/rails.sh
    command: ["bundle", "exec", "rails", "s", "-p", "3000", "-b", "0.0.0.0"]

  sidekiq:
    <<: *base
    image: chatwoot-rails:production
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
    command: ["bundle", "exec", "sidekiq", "-C", "config/sidekiq.yml"]
