version: '3'

services:
  base: &base
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        EXECJS_RUNTIME: 'Node'
        NODE_ENV: 'production'
        RAILS_ENV: 'production'
        RAILS_SERVE_STATIC_FILES: 'true'
    tty: true
    stdin_open: true
    image: chatwoot:production
    env_file: .env

  rails:
    <<: *base
    image: chatwoot-rails:production
    depends_on:
      - sidekiq
    ports:
      - 3000:3000
    env_file: .env
    environment:
      - EXECJS_RUNTIME=Node
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
    entrypoint: docker/entrypoints/rails.sh
    command: ["bundle", "exec", "rails", "s", "-p", "3000", "-b", "0.0.0.0"]

  sidekiq:
    <<: *base
    image: chatwoot-rails:production
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
    command: ["bundle", "exec", "sidekiq", "-C", "config/sidekiq.yml"]

  # webpack:
  #   <<: *base
  #   build:
  #     context: .
  #     dockerfile: ./docker/dockerfiles/webpack.Dockerfile
  #   image: chatwoot-webpack:development
  #   volumes:
  #     - ./:/app:delegated
  #     - node_modules:/app/node_modules # Node modules shared across containers
  #     - packs:/app/public/packs
  #     - cache:/app/tmp/cache
  #     - bundle:/usr/local/bundle
  #   ports:
  #     - "3035" # Webpack dev server
  #   environment:
  #     - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
  #     - NODE_ENV=development
  #     - RAILS_ENV=development
  #   entrypoint: docker/entrypoints/webpack.sh
  #   command: bin/webpack-dev-server

  postgres:
    image: postgres:12
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - chatwoot-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=chatwoot_production
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=3Vjph9gRnURNFUjdMMUK

  redis:
    image: redis:alpine
    restart: always
    volumes:
      - ./data/redis:/var/lib/redis/data
    ports:
      - '6379:6379'

volumes:
  chatwoot-volume:
      external: false
